# Site settings
title: Michael Hai Nguyen
email: mike@toch.im
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 44749D #80B3FF
  secondary: BDD1DE #FD6E8A
  secondary-dark: EBE7E0 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/miken
  - title: linkedin
    url: https://www.linkedin.com/pub/mike-nguyen/19/455/309
  - title: instagram
    url: http://instagram.com/mikengn

# Postal address (add as many lines as necessary)
address:
  - line: 292 Harvard St, Apt. 5
  - line: Cambridge, MA 02139

# Build settings
markdown: kramdown
permalink: pretty
